name: dockerhub-build-push

on:
  push:
    branches:
      - 'master'
      
jobs:
  
  docker:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Checkout Branch
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
            
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPO }}
          
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./images/crypto
          push: true
          tags: user/app:latest # eventually will make tag based on branch
      
